@props(['name'])

@php
// Map Mary UI icon names (o-*) to Phosphor names
$iconMap = [
    'o-plus' => 'plus',
    'o-x-mark' => 'x',
    'o-check' => 'check',
    'o-trash' => 'trash',
    'o-magnifying-glass' => 'magnifying-glass',
    'o-power' => 'power',
    'o-inbox' => 'tray',
    'o-bars-3' => 'list',
    'o-scale' => 'scales',
    'o-arrow-right-end-on-rectangle' => 'sign-in',
    'o-chevron-down' => 'caret-down',
    'o-chevron-up' => 'caret-up',
    'o-chevron-left' => 'caret-left',
    'o-chevron-right' => 'caret-right',
    'o-funnel' => 'funnel',
    'o-clock' => 'clock',
    'o-calendar' => 'calendar',
    'o-currency-euro' => 'currency-eur',
    'o-document-text' => 'file-text',
    'o-document' => 'file',
    'o-user' => 'user',
    'o-building-office' => 'buildings',
    'o-envelope' => 'envelope',
    'o-phone' => 'phone',
    'o-map-pin' => 'map-pin',
    'o-eye' => 'eye',
    'o-pencil' => 'pencil-simple',
    'o-archive-box' => 'archive',
    'o-arrow-path' => 'arrows-clockwise',
    'o-arrow-uturn-left' => 'arrow-u-up-left',
    'o-paper-airplane' => 'paper-plane-tilt',
    'o-cog' => 'gear',
    'o-chart-bar' => 'chart-bar',
    'o-banknotes' => 'money',
    'o-exclamation-triangle' => 'warning',
    'o-information-circle' => 'info',
    'o-check-circle' => 'check-circle',
    'o-x-circle' => 'x-circle',
    'o-link' => 'link',
    'o-share' => 'share',
    'o-arrow-down-tray' => 'download-simple',
    'o-arrow-up-tray' => 'upload-simple',
    'o-printer' => 'printer',
    'o-clipboard' => 'clipboard',
    'o-clipboard-document' => 'clipboard-text',
    'o-adjustments-horizontal' => 'sliders-horizontal',
    'o-home' => 'house',
    'o-tag' => 'tag',
    'o-ticket' => 'ticket',
    'o-calculator' => 'calculator',
    'o-credit-card' => 'credit-card',
    'o-receipt-percent' => 'receipt',
    'o-bell' => 'bell',
    'o-sun' => 'sun',
    'o-moon' => 'moon',
    'o-folder' => 'folder',
    'o-folder-open' => 'folder-open',
    'o-lock-closed' => 'lock',
    'o-lock-open' => 'lock-open',
    'o-key' => 'key',
    'o-shield-check' => 'shield-check',
    'o-shield-exclamation' => 'shield-warning',
    'o-wrench' => 'wrench',
    'o-sparkles' => 'sparkle',
    'o-star' => 'star',
    'o-heart' => 'heart',
    'o-globe-alt' => 'globe',
    'o-server' => 'server',
    'o-database' => 'database',
    'o-cloud' => 'cloud',
    'o-cloud-arrow-up' => 'cloud-arrow-up',
    'o-cloud-arrow-down' => 'cloud-arrow-down',
    'o-device-phone-mobile' => 'device-mobile',
    'o-computer-desktop' => 'desktop',
    'o-table-cells' => 'table',
    'o-play' => 'play',
    'o-pause' => 'pause',
    'o-stop' => 'stop',
    'o-arrow-right' => 'arrow-right',
    'o-arrow-left' => 'arrow-left',
    'o-arrow-up' => 'arrow-up',
    'o-arrow-down' => 'arrow-down',
    'o-arrows-right-left' => 'arrows-left-right',
    'o-arrows-up-down' => 'arrows-down-up',
    'o-question-mark-circle' => 'question',
    'o-book-open' => 'book-open',
    'o-academic-cap' => 'graduation-cap',
    'o-briefcase' => 'briefcase',
    'o-map' => 'map-trifold',
    'o-presentation-chart-bar' => 'presentation-chart',
    'o-presentation-chart-line' => 'chart-line-up',
    'o-chart-line-up' => 'chart-line-up',
    'o-square-3-stack-3d' => 'stack',
    'o-cube' => 'cube',
    'o-cube-transparent' => 'cube-transparent',
    'o-variable' => 'subtract-square',
    'o-hashtag' => 'hash',
    'o-at-symbol' => 'at',
    'o-flag' => 'flag',
    'o-bookmark' => 'bookmark-simple',
    'o-arrow-trending-up' => 'trend-up',
    'o-arrow-trending-down' => 'trend-down',
    'o-bolt' => 'lightning',
    'o-fire' => 'fire',
    'o-rocket-launch' => 'rocket-launch',
    'o-light-bulb' => 'lightbulb',
    'o-megaphone' => 'megaphone',
    'o-chat-bubble-left' => 'chat',
    'o-chat-bubble-left-ellipsis' => 'chat-dots',
    'o-chat-bubble-oval-left' => 'chat-text',
    'o-video-camera' => 'video-camera',
    'o-camera' => 'camera',
    'o-photo' => 'image',
    'o-gif' => 'gif',
    'o-face-smile' => 'smiley',
    'o-face-frown' => 'frown',
    'o-hand-thumb-up' => 'thumbs-up',
    'o-hand-thumb-down' => 'thumbs-down',
    'o-hand-raised' => 'hand',
    'o-wifi' => 'wifi-high',
    'o-signal' => 'signal-high',
    'o-battery-100' => 'battery-full',
    'o-battery-50' => 'battery-medium',
    'o-battery-0' => 'battery-empty',
    'o-chevron-up-down' => 'arrows-down-up',
    'o-ellipsis-vertical' => 'dots-three-vertical',
    'o-ellipsis-horizontal' => 'dots-three',
    'o-arrow-down-circle' => 'arrow-circle-down',
    'o-arrow-up-circle' => 'arrow-circle-up',
    'o-document-duplicate' => 'copy-simple',
    'o-arrow-top-right-on-square' => 'arrow-square-out',
    'o-arrow-down-on-square' => 'arrow-square-down',
    'o-paint-brush' => 'paint-brush',
    'o-swatch' => 'palette',
    'o-qr-code' => 'qr-code',
    'o-barcode' => 'barcode',
    'o-currency-dollar' => 'currency-dollar',
    'o-currency-pound' => 'currency-gbp',
    'o-currency-yen' => 'currency-jpy',
    'o-building-library' => 'bank',
    'o-building-storefront' => 'storefront',
    'o-truck' => 'truck',
    'o-shopping-cart' => 'shopping-cart',
    'o-shopping-bag' => 'shopping-bag',
    'o-gift' => 'gift',
    'o-trophy' => 'trophy',
    'o-musical-note' => 'music-note',
    'o-film' => 'film-strip',
    'o-microphone' => 'microphone',
    'o-speaker-wave' => 'speaker-high',
    'o-speaker-x-mark' => 'speaker-x',
    'o-rss' => 'rss',
    'o-newspaper' => 'newspaper',
    'o-lifebuoy' => 'lifebuoy',
    'o-identification' => 'identification-card',
    'o-finger-print' => 'fingerprint',
    'o-no-symbol' => 'prohibit',
    'o-minus' => 'minus',
    'o-minus-circle' => 'minus-circle',
    'o-receipt-refund' => 'receipt',
    'o-clipboard-document-list' => 'clipboard-text',
    'o-cog-6-tooth' => 'gear-six',
    'o-list-bullet' => 'list-bullets',
    'o-cpu-chip' => 'cpu',
    'o-cog-8-tooth' => 'gear',
    'o-puzzle-piece' => 'puzzle-piece',
    'o-clipboard-document-check' => 'clipboard-text',
    'o-users' => 'users-three',
    'o-user-group' => 'users-three',
    'o-document-arrow-up' => 'file-arrow-up',
    'o-document-arrow-down' => 'file-arrow-down',
    'o-document-check' => 'file-check',
    'o-pencil-square' => 'pencil-simple-line',
    'o-arrow-right' => 'arrow-right',
    'o-arrow-left' => 'arrow-left',
    'o-arrow-up' => 'arrow-up',
    'o-arrow-down' => 'arrow-down',
    'o-spinner' => 'spinner',
];

$phosphorName = $iconMap[$name] ?? $name;

// Map w-* h-* classes to font-size for Phosphor font icons
$sizeMap = [
    'w-3' => 'text-xs', 'w-3.5' => 'text-xs',
    'w-4' => 'text-base', 'w-5' => 'text-lg',
    'w-6' => 'text-xl', 'w-7' => 'text-2xl',
    'w-8' => 'text-2xl', 'w-10' => 'text-3xl',
    'w-12' => 'text-4xl',
];
$extraClasses = '';
foreach ($sizeMap as $w => $fs) {
    if (str_contains($attributes->get('class', ''), $w)) {
        $extraClasses .= ' ' . $fs;
        break;
    }
}
@endphp

<i {{ $attributes->merge(['class' => 'ph ph-' . $phosphorName . $extraClasses . ' inline-flex items-center justify-center', 'aria-hidden' => 'true']) }}></i>
