query CreditNotesList($page: Int!, $first: Int!) {
  creditNotes(page: $page, first: $first) {
    data {
      id
      number
      date
      status
      total_gross
      is_sdi_editable
      contact { id name }
    }
    paginatorInfo {
      currentPage
      lastPage
      total
      firstItem
      lastItem
      hasMorePages
    }
  }
}
